# Generated by Django 5.0.3 on 2024-04-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_alter_properties_bathrooms_alter_properties_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
